#!/bin/sh
# websockify2 configure script
# Detects platform, compiler, and OpenSSL paths

set -e

PREFIX="${PREFIX:-/usr/local}"
CC="${CC:-cc}"
CFLAGS="${CFLAGS:--O2 -Wall -Wextra -Wpedantic}"
LDFLAGS="${LDFLAGS:-}"
LIBS=""

# Detect OS
OS="$(uname -s)"
case "$OS" in
    Linux)   PLATFORM="linux"   ;;
    Darwin)  PLATFORM="darwin"  ;;
    FreeBSD) PLATFORM="freebsd" ;;
    MINGW*|MSYS*|CYGWIN*) PLATFORM="windows" ;;
    *)       PLATFORM="unknown" ;;
esac

echo "Platform: $PLATFORM ($OS)"

# Detect compiler
$CC --version >/dev/null 2>&1 || { echo "Error: C compiler not found ($CC)"; exit 1; }
echo "Compiler: $CC"

# Find OpenSSL
find_openssl() {
    # Try pkg-config first
    if pkg-config --exists openssl 2>/dev/null; then
        SSL_CFLAGS=$(pkg-config --cflags openssl)
        SSL_LIBS=$(pkg-config --libs openssl)
        echo "OpenSSL found via pkg-config"
        return 0
    fi

    # Common paths
    for dir in /usr /usr/local /opt/homebrew /usr/local/opt/openssl \
               /usr/local/opt/openssl@3 /usr/local/opt/openssl@1.1 \
               /opt/local; do
        if [ -f "$dir/include/openssl/ssl.h" ]; then
            SSL_CFLAGS="-I$dir/include"
            SSL_LIBS="-L$dir/lib -lssl -lcrypto"
            echo "OpenSSL found at $dir"
            return 0
        fi
    done

    # Try system default
    if [ -f "/usr/include/openssl/ssl.h" ]; then
        SSL_CFLAGS=""
        SSL_LIBS="-lssl -lcrypto"
        echo "OpenSSL found in system paths"
        return 0
    fi

    echo "Warning: OpenSSL not found, SSL support disabled"
    SSL_CFLAGS=""
    SSL_LIBS=""
    return 1
}

HAS_SSL=0
if find_openssl; then
    HAS_SSL=1
    CFLAGS="$CFLAGS $SSL_CFLAGS"
    LIBS="$LIBS $SSL_LIBS"
fi

# Platform-specific flags
case "$PLATFORM" in
    linux)
        LIBS="$LIBS -lpthread"
        CFLAGS="$CFLAGS -D_GNU_SOURCE"
        ;;
    darwin)
        # Nothing extra needed
        ;;
    freebsd)
        LIBS="$LIBS -lpthread"
        ;;
    windows)
        LIBS="$LIBS -lws2_32"
        CFLAGS="$CFLAGS -D_WIN32_WINNT=0x0602"
        ;;
esac

# Write config.mk
cat > config.mk << EOF
# Generated by configure.sh — $(date)
PLATFORM = $PLATFORM
CC       = $CC
CFLAGS   = $CFLAGS
LDFLAGS  = $LDFLAGS
LIBS     = $LIBS
PREFIX   = $PREFIX
HAS_SSL  = $HAS_SSL
EOF

echo ""
echo "Configuration written to config.mk"
echo "  Platform:  $PLATFORM"
echo "  Compiler:  $CC"
echo "  CFLAGS:    $CFLAGS"
echo "  LIBS:      $LIBS"
echo "  SSL:       $([ $HAS_SSL -eq 1 ] && echo 'yes' || echo 'no')"
echo ""
echo "Run 'make' to build."
